### ISSUE TITLE
Issues when adding concatenated rule (payload_expr_complete assertion failure)

### ISSUE THREAD

**Issue by msdean** [google/nftables#156]
Following [this issue](https://github.com/google/nftables/issues/154) (which was resolved), I'm trying to add a rule to match a concatenated set.
Given the following concatenated set:
```
set ip6_set {
                type ipv6_addr . ipv6_addr . inet_service
                flags interval
                elements = {
                             777c:ab4b:85f0:1614:49e5:d29b:aa7b:cc90 . 8709:1cb9:163e:9b55:357f:ef64:708a:edcb . 1-60000 
                }
}
```
I'm trying to add the following rule (which works fine using the cmdline tool):
```
chain ip6_filter {
                ip6 saddr . ip6 daddr . tcp dport @ip6_set jump some_target
}
```

This is the code I'm using to add the lines:

```
func matchIPv6Set(set *nftables.Set, jumpTarget string) []expr.Any {
	var (
		ip6OffsetSrc uint32 = 8
		ip6OffsetDst uint32 = 24
		ip6AddrLen   uint32 = 16
		// l4ProtoOffset uint32 = 6
		l4PortLen   uint32 = 2
		l4OffsetDst uint32 = 2
	)

	//ip6 saddr . ip6 daddr . tcp dport @<set> jump <jumpTarget>
	return []expr.Any{
		// Store protocol type to register 1
		&expr.Meta{
			Key:      expr.MetaKeyL4PROTO,
			Register: 1,
		},
		// Match IP Family
		&expr.Cmp{
			Op:       expr.CmpOpEq,
			Register: 1,
			Data:     []byte{byte(nftables.TableFamilyIPv6)},
		},
		
		// Store the destination IP address to register 8 (first 16B register)
		&expr.Payload{
			DestRegister: 8,
			Base:         expr.PayloadBaseNetworkHeader,
			Offset:       ip6OffsetSrc,
			Len:          ip6AddrLen,
		},
		// Store the destination IP to register 12 (8+4, as ipv6 addr is 16B)
		&expr.Payload{
			DestRegister: 12,
			Base:         expr.PayloadBaseNetworkHeader,
			Offset:       ip6OffsetDst,
			Len:          ip6AddrLen,
		},
		// Store the destination port to register 16 (12+4, as ipv6 addr is 16B)
		&expr.Payload{
			DestRegister: 16,
			Base:         expr.PayloadBaseTransportHeader,
			Offset:       l4OffsetDst,
			Len:          l4PortLen,
		},

		// Match from target set
		&expr.Lookup{
			SourceRegister: 1,
			SetName:        set.Name,
			SetID:          set.ID,
		},

		&expr.Verdict{
			Kind:  expr.VerdictJump,
			Chain: jumpTarget,
		},
	}
}

```

Rule seems to be added just fine, but when I try to list the table using the cmdline tool I get:
`nft: payload.c:892: payload_expr_complete: Assertion 'desc->base == expr->payload.base' failed.`

I have a suspicion that it has something to do with the fact that the concatenated expression has a mix of payload bases (Network+Transport). 

Note:
I get the same output when using the "legacy" DestRegister(s) 1,2,3.

I do see the rule being added when dumping all the rules in my code, but the cmdline tool breaks with the assertion error.

I'm using latest nftables:
nftables (bcad476126f07691b7bc3657d1ade257d469e715)
libmnl (2a3e927ec79e3a52d8cea60ccdfb8699b8a0d56e)
libnftnl (e2514c0eff4da7e8e0aabd410f7b7d0b7564c880)
On kernel 5.13 (Ubuntu 20.04LTS).

With latest package version (which includes the set concatenation fix).

**Comment by stapelberg** [comment]
Maybe @turekt has any ideas?

**Comment by turekt** [comment]
Hi,

I managed to reproduce your bug and fix it by changing the code of the `matchIPv6Set` function you have provided. The fix for your issue was to change the only `expr.Cmp` struct in the list from:
```
&expr.Cmp{
	Op:       expr.CmpOpEq,
	Register: 1,
	Data:     []byte{byte(nftables.TableFamilyIPv6)},
},
```

to:
```
&expr.Cmp{
	Op:       expr.CmpOpEq,
	Register: 1,
	Data:     []byte{unix.IPPROTO_TCP},
},
```

Note that results may vary depending on your table family. What I am observing is that when I use `table inet filter`, there is an additional `meta nfproto` added in the beginning of the message which specifies that the network layer protocol being matched is IPv6. This is logical for an `inet` table since it can also have IPv4 rules. On the other hand, when using the `table ip6 filter` the `meta nfproto` expression is omitted and I think that this happens because the table type `ip6` already suggests only IPv6 on the network layer. Because of this, the `meta l4proto` only has to specify which L4 protocols are being matched (e.g. `unix.IPPROTO_TCP`). 

```
$ sudo nft list ruleset
table ip6 filter {
	set ip6_set {
		type ipv6_addr . ipv6_addr . inet_service
		flags interval
		elements = { 777c:ab4b:85f0:1614:49e5:d29b:aa7b:cc90 . 8709:1cb9:163e:9b55:357f:ef64:708a:edcb . 50000-60000 }
	}

	chain output {
		counter packets 8 bytes 2020
	}

	chain ip6_filter {
	}
}
$ go build -o main main.go && sudo ./main
$ sudo nft list ruleset
table ip6 filter {
	set ip6_set {
		type ipv6_addr . ipv6_addr . inet_service
		flags interval
		elements = { 777c:ab4b:85f0:1614:49e5:d29b:aa7b:cc90 . 8709:1cb9:163e:9b55:357f:ef64:708a:edcb . 50000-60000 }
	}

	chain output {
		counter packets 8 bytes 2020
	}

	chain ip6_filter {
		ip6 saddr . ip6 daddr . tcp dport @ip6_set jump output
	}
}
```

You can find more information on matching here `https://wiki.nftables.org/wiki-nftables/index.php/Matching_packet_metainformation`.

Keep in mind that I might be wrong in some of my assumptions. They are solely based on the nftables messages that I am seeing and the documentation/code I have read.

I hope that this resolves your issue.

**Comment by msdean** [comment]
@turekt seems like you're right. Your change did solve my issue, and your explanation also makes sense.
Thank you once again :)
