### ISSUE TITLE
invalid operation: signed shift count 8 (untyped int constant) requires go1.13 or later

### ISSUE THREAD

**Issue by thediveo** [google/nftables#158]
Trying to use `nftables` in a Go workspace causes the following warning/error (for instance, when working with VSCode and the official go add-on):

```
invalid operation: signed shift count 8 (untyped int constant) requires go1.13 or later
```

Is there something blocking upgrading the `go.mod` to 1.17 or 1.18?

**Comment by stapelberg** [comment]
No blockers that I know of. Bumped the go.mod version to 1.17, so this should be fixed

**Comment by gustavo-iniguez-goya** [comment]
Depending on go >= 1.16 version will add glibc >= 2.32 as dependency, which is not available on older distros (due to [pthread_sigmask](https://github.com/containers/toolbox/issues/529#issuecomment-677753229))

On our case, we're compiling with go1.15 to workaround this problem (we don't offer a compilation/package of opensnitch per distribution). For now we'll use nftables@76ed01e

**Comment by stapelberg** [comment]
Could opensnatch be built without cgo, to produce a statically linked binary without glibc dependencies?

Go 1.15 is quite old at this point. I see much better performance in Go 1.18.
