### ISSUE TITLE
With nftables.AsLasting(), Flush() does not return an error although rules are not executed

### ISSUE THREAD

**Issue by ziggie1984** [google/nftables#170]
# Problem 
I was trying to add a firewall rule which was not supported by my backend of the linux machine (nftables v0.9.0 (Fearless Fosdick)
I was not able to add a NAT Chaintype into an inet table. But the flush command did not raise any errors and it was very hard to debug the problem bc no errors were returned. When trying to add the Chain with the linux tool "nft" it threw an error telling me something like:

```
 sudo nft add chain inet wg0 test-chain2 '{type route  hook output  priority 100; policy accept; }'
Error: Could not process rule: No such file or directory
add chain inet wg0 test-chain2 {type route  hook output  priority 100; policy accept; }
```
The ip table was recognized

# Expected Behaviour

The Wrapper throws an error when the backend is not able to add the functionality into the ruleset

**Comment by ziggie1984** [comment]
Both tables did exist:

`sudo nft list tables`:
```
table ip nat
table ip filter
table inet wg0
table ip wg0
```

**Comment by stapelberg** [comment]
Sorry, I’m not following. Can you provide the full Go source of the program that isn’t working please?

**Comment by ziggie1984** [comment]
https://github.com/ziggie1984/nftables_sample/blob/master/main.go

This example tries to add 2 route chains into the output hook, the ip table works, the inet table does not, after running the binary:

```
table ip wg0 {
	chain base-chain {
		type route hook output priority -100; policy accept;
	}
}
table inet wg0_inet {
}
```

**Comment by ziggie1984** [comment]
not sure when route and nat chaintypes were added to the nftable set but binary works perfectly on a ubuntu with nftables nftables v1.0.2 (Lester Gooch):

After executing the binary:

```
table ip wg0 {
	chain base-chain {
		type route hook output priority -100; policy accept;
	}
}
table inet wg0_inet {
	chain base-chain {
		type route hook output priority -100; policy accept;
	}
}
```

**Comment by stapelberg** [comment]
I can only reproduce the problem with your program on Debian 10 (Linux 4.19).

It turns out that the error reporting is only broken when using the recently-added lasting nftables connection support: as soon as I use `nftClient := &nftables.Conn{}` to open a connection, I do get an error from `Flush()`: `Receive: netlink receive: no such file or directory`

@thediveo Could you take a look at this please? Seems like there’s a bug in the lasting connection code.

**Comment by thediveo** [comment]
Does this happen only when long-lasting was requested or does it happen always?

**Comment by stapelberg** [comment]
As I wrote, the error reporting is only broken when using the recently-added lasting nftables connection support.

**Comment by thediveo** [comment]
hehe, race condition on the title.

**Comment by thediveo** [comment]
I'm not yet fully understanding the bug report. Which `Flush` call should fail, the first one or a later one? Is the example linked to intended to fail? Does this somehow depend on the kernel and nftables version ("I can **only** ...", my emphasis)?

From looking at the code again and again I don't yet see any obvious bug, unfortunately.

**Comment by thediveo** [comment]
I've updated my previous questions (boo!) so just noticing that there's no error checking on the other flushes, so do we actually know that this isn't something just carried over because we now keep the connection open instead of throwing it away?

**Comment by stapelberg** [comment]
> hm, I don't have access to a Debian system that old.

An easy fix for that is to create a VM and install debian 10. gnome-boxes is an easy to use VM program :)

---

Looking at this issue more, one piece of the puzzle is the duplicated `AddChain()` call in: https://github.com/ziggie1984/nftables_sample/blob/2331b08955e78c20c3520c0a94611bb54c37bf76/main.go#L25-L33

When I remove one of the `AddChain()` calls, the example also works (i.e. prints an error message for the last, non-working request) with a lasting nftables connection.

I think in the scenario where we send two `AddChain()` calls, we still only `Receive()` one error message, and then for the next `AddTable()` call, we receive the error message from the previous `AddChain()` call.

This only matters when using a lasting connection — when re-connecting for each `Flush()`, at least the first `NLMSG_ERROR` reply will always match the first request sent, papering over this issue.

The problem might be how we call `(mdlayher/netlink.Conn).Receive()`: https://github.com/google/nftables/blob/1f0380f5c76eb92b9bc92aa1d20585e6871ae4b3/conn.go#L185

I’m thinking we might need to call it an appropriate number of times based on what we send. `mdlayher/netlink` has its own handling for multi-part messages, but I think multi-part messages might be orthogonal? Perhaps we just need to count how many `netlink.Acknowledge` flags we send out?

cc @mdlayher in case you happen to know off the top of your head how acknowledgement/error handling is supposed to be done with netlink :)

**Comment by thediveo** [comment]
@stapelberg unfortunately, my current RPi4+ 8GB dev system is incredibly slow when slapping VMs on it, even if the USB3 SSD (or because of it). Otherwise it is fine for almost all tasks.

Many thanks and kudos for spending the effort to further drill down and isolate this issue, as I would have been lost in netlink territority having it only used indirectly via modules such as the famous pyroute2 or Go's netlink, keeping a healthy distance from the protocol bits.

On a side note, long time ago, the good IT/OT people at a large car manufacturer deeply mused whether to sell me at a premium as a tester serf to a big bluish company or alternatively make me disappear forever, as whatever IT or OT system I touch soon exhibits bugs not seen before. Seems my "aura" worked again turning up issues not seen before. 😊

**Comment by ziggie1984** [comment]
Thanks a lot for taking care of this issue 👍
