### ISSUE TITLE
map support

### ISSUE THREAD

**Issue by rampxxxx** [google/nftables#186]
Hi, 
Know that set and vmap (via IsMap in Set) are supported but I don't think that "proper" [maps](https://wiki.nftables.org/wiki-nftables/index.php/Maps) are supported , isn't it? , is there any plan to support maps?

Please sorry is they are already supported in that case could any point to any test or code example for that?

**Comment by turekt** [comment]
Hi,

not sure if there is a specific feature that you are referring to since I am not aware of what "proper map" stands for.

I have adapted an example code from another issue to implement the first _Named maps_ example you have linked:
```
package main

import (
	"log"
	"net/netip"

	"github.com/google/nftables"
)

func main() {
	c, err := nftables.New()
	if err != nil {
		panic(err)
	}

	table := &nftables.Table{
		Name:   "filter",
		Family: nftables.TableFamilyIPv4,
	}

	set2 := &nftables.Set{
		Table:         table,
		Name:          "test-concat2",
		IsMap:         true,
		KeyType:       nftables.TypeInetProto,
		DataType:      nftables.TypeIPAddr,
	}

	err = c.AddSet(set2, nil)
	check(err)

	addr := netip.MustParseAddr("1.1.1.1").As4()
	var el2 nftables.SetElement
	el2.Key = []byte{80}
	el2.Val = addr[:]

	err = c.SetAddElements(set2, []nftables.SetElement{el2})
	check(err)

	log.Println("creating and adding element to second set")
	err = c.Flush()
	check(err)
}
```

You can see a few more examples in the `nftables_test.go` file, e.g. the `TestMap` function: https://github.com/google/nftables/blob/cbeb0fb1eccf9ef582c20982c72e73107d1898a5/nftables_test.go#L4866

I hope that this resolves your issue.

**Comment by rampxxxx** [comment]
Thank you!.
I was thinking that vmap were different from map (which I was calling proper maps) but it just seems that vmap ask for elements with key:veredict and map just ask for key:data .
